name: diversify
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - numpy=1.9
    - pandas=0.23.4
    - pip=18.1
    - pip:
          - spotipy==2.4.4
          - python-dotenv==0.9.1
