name: diversify-viz
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - bokeh=0.12
    - numpy=1.9
    - altair=2.2.2
    - pandas=0.23.4
    - seaborn=0.9.0
    - pip=18.1
    - pip:
          - spotipy==2.4.4
          - python-dotenv==0.9.1
